### ISSUE TITLE
Facebook API v2.4 no longer supports read_mailbox

### ISSUE THREAD

**Issue by benkoller** [TigerApps/Facebook-Slack-Integration#1]
Hi,

ever since Facebook switched to v2.4 read_mailbox, manage_notifications and read_stream are no longer available as there is a Facebook Messenger API now.

Any chance you would upgrade your app to the new APIs?

Cheers,
Ben

**Comment by WhiteHatArpit** [comment]
Thanks Ben for pointing it out! I will look into the new FB api and try to solve the things as soon as I can.

**Comment by WhiteHatArpit** [comment]
#3
