### ISSUE TITLE
Port to newer version of FB apis

### ISSUE THREAD

**Issue by WhiteHatArpit** [TigerApps/Facebook-Slack-Integration#3]
The newer version of FB apis don't support many permissions and work differently for some. Need to port the methods accordingly.

**Comment by ghost** [comment]
In place of the other permissions, would "user_notifications" allow you to access enough information? 
Is port 8080 still the correct port or should I be able to use 8000 or 443?
I am still waiting for Facebook to grant me the "user_notifications" usage. I currently get the following message in Slack.
###############################################

No new Notifications for me.

###############################################
Couldnt Parse

Is "Couldnt Parse" expected? It comes from line 32 in webhook.py and references Messages. I am not really concerned with fetching messages. I just want to see FB notifications.

**Comment by WhiteHatArpit** [comment]
Hi!

You would have to look into the meaning of the said Facebook permission.

You can use any open port according to where you wanna deploy the server and serve.
`port = int(os.environ.get('PORT', 8000))`
means that if PORT is not found in environment variables, it would run on 8000.

`Couldnt Parse` is coming because Facebook stopped supporting messages fetching. If you want to fetch only Notifications, you would have to edit the webhook.py. Copy this whole in it:

```
import requests
import json
from parse import parse,parsenotif
from fetch import fetch,fetchnotif

# fetch, parse and post to slack
def posttoSlack(slack_url,app_token,access_token,packetm,packetn,count):

    # for debugging token, check if valid
    debug_url ="https://graph.facebook.com/debug_token?input_token="+ access_token +"&access_token=" + app_token
    prev_packetm = packetm
    prev_packetn = packetn

    try:
        response = requests.get(debug_url)
        data = json.loads(response.text)

        # validation of token
        if 'error' in data.keys():
            packetm = "access_token not valid"
        else:
            # fetch messages data
            # try:
            #   data = fetch(access_token) 
            # except:
            #   packetm = "Couldnt Fetch"
            # # parse fetched message data
            # try:
            #   packetm = parse(data)
            # except:
            #   packetm = "Couldnt Parse"

            # change this if you need to get updated for notifications more frequently
            if count % 1 == 0:
                # fetch notifications data 
                try:
                    data = fetchnotif(access_token)
                except:
                    packetn = "Couldnt Fetch Notif"
                # parse notifications data
                try:
                    packetn = parsenotif(data)
                except:
                    packetn = "Couldnt Parse Notif"


    except:
        packetm = "Couldnt Debug"   

    # prepare packet with messages and notifications
    if count % 1 == 0:
        # post to slack if not same as earliar
        # if packetn+packetm != prev_packetn+prev_packetm:
            payload={"text": packetn }
            response = requests.post(slack_url,json.dumps(payload))

    # prepare packet with messages only 
    else:
        # post to slack if not same as earliar
        if packetm != prev_packetm:
            payload={"text": packetm }
            response = requests.post(slack_url,json.dumps(payload))

    return packetm,packetn
```

I hope it solves your problem.

**Comment by WhiteHatArpit** [comment]
Porting doesn't seem plausible at the moment.
